In [1]:
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('Dataset.csv')
data

N     P     K  temperature   humidity        ph    rainfall   label  \
0      90  42.0  43.0    20.879744  82.002744  6.502985  203.983200    rice   
1      85  58.0  41.0    22.000940  80.319644  7.038096  226.655537    rice   
2      60  55.0  44.0    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35.0  40.0    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42.0  42.0    20.130175  81.604873  7.628473  262.717340    rice   
...   ...   ...   ...          ...        ...       ...         ...     ...   
2195  107  34.0  32.0    26.774637  66.413269  6.780064         NaN  coffee   
2196   99  15.0  27.0    27.417112  56.636362  6.086922  127.924610  coffee   
2197  118  33.0  30.0    24.131797  67.225123  6.362608  173.322839  coffee   
2198  117  32.0  34.0    26.272418  52.127394  6.758793  127.175293  coffee   
2199  104  18.0  30.0    23.603016  60.396475  6.779833  140.937041  coffee   

                             Yield                  Watering  \
0         22-25 quintals per acre              10 mm per day   
1         22-25 quintals per acre              10 mm per day   
2         22-25 quintals per acre              10 mm per day   
3         22-25 quintals per acre              10 mm per day   
4         22-25 quintals per acre              10 mm per day   
...                            ...                       ...   
2195   4 to 7 quintals per hectare  1200 to 1800 mm per year   
2196   4 to 7 quintals per hectare  1200 to 1800 mm per year   
2197   4 to 7 quintals per hectare  1200 to 1800 mm per year   
2198   4 to 7 quintals per hectare  1200 to 1800 mm per year   
2199   4 to 7 quintals per hectare  1200 to 1800 mm per year   

                                              Pesticide  
0     Lambda-cyhalothrin, malathion and zeta-cyperme...  
1     Lambda-cyhalothrin, malathion and zeta-cyperme...  
2     Lambda-cyhalothrin, malathion and zeta-cyperme...  
3     Lambda-cyhalothrin, malathion and zeta-cyperme...  
4     Lambda-cyhalothrin, malathion and zeta-cyperme...  
...                                                 ...  
2195  White stem borer, coffee berry borer, Shoot ho...  
2196  White stem borer, coffee berry borer, Shoot ho...  
2197  White stem borer, coffee berry borer, Shoot ho...  
2198  White stem borer, coffee berry borer, Shoot ho...  
2199  White stem borer, coffee berry borer, Shoot ho...  

[2200 rows x 11 columns]

In [3]:
data.dropna(inplace=True)

In [4]:
for item in data['label'].unique():
	print(item, data[data['label']==item]['Yield'].unique())

rice ['22-25 quintals per acre ']
maize ['10-20 quintals per acre']
chickpea ['8-10 quintals per acre']
kidneybeans ['7-8 quintals per acre']
pigeonpeas ['6-8 quintals per acre']
mothbeans ['12-25 quintals per acre']
mungbean ['5-6 quintals per acre']
blackgram ['7-8 quintals per acre']
lentil ['15-20 quintals per acre']
pomegranate ['80 quintals per acre']
banana ['180 quintals per acre']
mango ['2.5 to 3 tonnes per acre']
grapes ['20 to 25 tonnes per acre']
watermelon ['30 to 45 tonnes per acre ']
muskmelon ['12 to 15 tonnes per hectare']
apple ['54 to 67 quintals per acre']
orange ['27 quintals per hectare']
papaya ['75 to 100 tonnes per hectare']
coconut ['2000 to 3000 nuts per acre']
cotton ['40 to 50 quintals per acre ']
jute ['45 to 50 tonnes per hectare']
coffee [' 4 to 7 quintals per hectare']


Yield value is same for each label so it does not need to be predicted

In [5]:
for item in data['label'].unique():
	print(item, data[data['label']==item]['Watering'].unique())

rice ['10 mm per day']
maize ['2.5 to 4.2 mm per day']
chickpea ['10 mm per day']
kidneybeans ['300 to 500 mm off 6-7 times/growth period']
pigeonpeas ['200-250mm']
mothbeans ['500-750 mm']
mungbean ['50mm of 3 to 5 waterings during the growing condition']
blackgram ['200 to 300 mm with an interval of 7 to 10 days']
lentil ['150 to 250 mm ']
pomegranate ['5.3 mm per day']
banana ['1800 to 2000 mm per annum with an interval ot 7 to 8 days']
mango ['25mm per week']
grapes ['25mm per week']
watermelon ['500mm per week']
muskmelon ['400 to 600 mm per totoal crop periodd']
apple ['25 mm with an interval of 7 to 10 days']
orange ['35 to 105 litres per plant ']
papaya ['20 to 25 litres per plant in every 2 weeks']
coconut ['40 to 200 litres per tree in every 4 days']
cotton ['700 to 1000 mm for total crop period']
jute ['500 mm for the total crop period with an interval of 15 days']
coffee ['1200 to 1800 mm per year']


Watering value is the same for each label so it does not need to be predicted

In [6]:
for item in data['label'].unique():
	print(item, data[data['label']==item]['Pesticide'].unique())

rice ['Lambda-cyhalothrin, malathion and zeta-cypermethrin']
maize ['Methyl demeton 25 EC 500 ml/ha. Carbofuran 3%CG 33.3 kg/ha. Dimethoate 30%EC 1155 ml/ha. Methyl demeton 25% EC 1000 ml/ha. Phorate 10%CG 10 kg/ha.']
chickpea ['Foliar spray of 2% urea, Pendimethalin 30% EC, Chlorpyriphos insecticide'
 'Foliar spray of 2% urea, Pendimethalin L30030% EC, Chlorpyriphos insecticide']
kidneybeans ['glyphosate, 1.5% dieldrin with 3% aramite,  2% parathion']
pigeonpeas ['pod borer, pod borer complex, pod fly']
mothbeans ['pendimethalin 30%, imazamox 50 g/ ha']
mungbean ['diafenthiuron 50 wp, acetamiprid 20 sp']
blackgram ['Dimethoate 30% EC, Methyl demeton 25%EC, Imidacloprid 17.8 SL']
lentil ['Paraquat, diquat or glyphosate']
pomegranate ['Dimethoate (0.03%) or Malathion (0.1%) ']
banana ['carbaryl (1g/liter) or chlorpyriphos (2.5 ml/lit)']
mango ['0.15% Carbaryl or 0.04% Monocrotophos or 0.05% Phosphamidon or 0.05% Methyl Parathion']
grapes ['Imidacloprid, fluazinam ,  fludioxonil']
waterm

Pesicide is also same for each label so it does not need to be predicted

In [7]:
crops = {}
for item in data['label'].unique():
	val = data[data['label'] == item]
	crops[item] = list(val.iloc[0][-3:])

f = open('cropsDict.pkl', 'wb')
pickle.dump(crops, f)
f.close()

In [8]:
x = data.drop(['Watering', 'Yield', 'Pesticide', 'label'], axis=1).to_numpy()
y = data[['label']].to_numpy()
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=101)

In [9]:
lr = LogisticRegression()
lr.fit(xtrain, ytrain)
f = open('logisticRegression.pkl', 'wb')
pickle.dump(lr, f)
f.close()

In [10]:
print('Training Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytrain, lr.predict(xtrain)))
print('Accuracy :', accuracy_score(ytrain, lr.predict(xtrain)))

Training Data Metrics :
Confusion Matrix :
[[73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 81  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 64  0  0  0  0  0  0  0  0  1  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 67  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 69  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 66  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0 68  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0 72  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0 76  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0  0  0 65  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 80  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  0  0  0  1  0  0 62  1  0  0  0  0  

In [11]:
print('Testing Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytest, lr.predict(xtest)))
print('Accuracy :', accuracy_score(ytest, lr.predict(xtest)))

Testing Data Metrics :
Confusion Matrix :
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  2  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0 15  2  0  0  0  0  0

In [12]:
# Logistic Regression Inputs

n = int(input('Enter N Value : '))
p = float(input('Enter P Value : '))
k = float(input('Enter K Value : '))
temp = float(input('Enter temperature : '))
humidity = float(input('Enter humidity : '))
ph = float(input('Enter ph : '))
rain = float(input('Enter rainfall : '))

inp = np.array([n, p, k, temp, humidity, ph, rain]).reshape(-1, 7)
output = lr.predict(inp)[0]
print('Crop :', output)
print('Yield :', crops[output][0])
print('Watering :', crops[output][1])
print('Pesticide :', crops[output][2])

Crop : rice
Yield : 22-25 quintals per acre 
Watering : 10 mm per day
Pesticide : Lambda-cyhalothrin, malathion and zeta-cypermethrin


In [13]:
rfc = RandomForestClassifier()
rfc.fit(xtrain, ytrain)
f = open('randomForestClassifier.pkl', 'wb')
pickle.dump(rfc, f)
f.close()

In [14]:
print('Training Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytrain, rfc.predict(xtrain)))
print('Accuracy :', accuracy_score(ytrain, rfc.predict(xtrain)))

Training Data Metrics :
Confusion Matrix :
[[73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 81  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 71  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 67  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 66  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 72  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 79  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 74  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 80  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 70  0  0  0  0  0  

In [15]:
print('Testing Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytest, rfc.predict(xtest)))
print('Accuracy :', accuracy_score(ytest, rfc.predict(xtest)))

Testing Data Metrics :
Confusion Matrix :
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0

In [17]:
# Random Forest Classifier Inputs

n = int(input('Enter N Value : '))
p = float(input('Enter P Value : '))
k = float(input('Enter K Value : '))
temp = float(input('Enter temperature : '))
humidity = float(input('Enter humidity : '))
ph = float(input('Enter ph : '))
rain = float(input('Enter rainfall : '))

inp = np.array([n, p, k, temp, humidity, ph, rain]).reshape(-1, 7)
output = rfc.predict(inp)[0]
print('Crop :', output)
print('Yield :', crops[output][0])
print('Watering :', crops[output][1])
print('Pesticide :', crops[output][2])

Crop : coffee
Yield :  4 to 7 quintals per hectare
Watering : 1200 to 1800 mm per year
Pesticide : White stem borer, coffee berry borer, Shoot hole borer, MALATHION 50% E.C


In [18]:
svc = SVC()
svc.fit(xtrain, ytrain)
f = open('supportVectorClassifier.pkl', 'wb')
pickle.dump(svc, f)
f.close()

In [19]:
print('Training Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytrain, svc.predict(xtrain)))
print('Accuracy :', accuracy_score(ytrain, svc.predict(xtrain)))

Training Data Metrics :
Confusion Matrix :
[[73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 81  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 71  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 75  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 79  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 67  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 73  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 66  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 76  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 72  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 78  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 73  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 80  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  5  0  0 63  0  0  0  0  0  

In [20]:
print('Testing Data Metrics :\nConfusion Matrix :')
print(confusion_matrix(ytest, svc.predict(xtest)))
print('Accuracy :', accuracy_score(ytest, svc.predict(xtest)))

Testing Data Metrics :
Confusion Matrix :
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 22  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 19  0  0  0  0  0  0

In [21]:
# Support Vector Classifier Inputs

n = int(input('Enter N Value : '))
p = float(input('Enter P Value : '))
k = float(input('Enter K Value : '))
temp = float(input('Enter temperature : '))
humidity = float(input('Enter humidity : '))
ph = float(input('Enter ph : '))
rain = float(input('Enter rainfall : '))

inp = np.array([n, p, k, temp, humidity, ph, rain]).reshape(-1, 7)
output = svc.predict(inp)[0]
print('Crop :', output)
print('Yield :', crops[output][0])
print('Watering :', crops[output][1])
print('Pesticide :', crops[output][2])

Crop : jute
Yield : 45 to 50 tonnes per hectare
Watering : 500 mm for the total crop period with an interval of 15 days
Pesticide : Carbofuran 03.00% CG, Phosalone 35.00% EC, Quinalphos 25.00% EC
